/*
	Copyright (c) 2004-2013, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/

//>>built
(function(d,q){var g,m=function(){},h=function(f){for(var a in f)return 0;return 1},c={}.toString,n=function(f){return"[object Function]"==c.call(f)},l=function(f){return"[object String]"==c.call(f)},b=function(f){return"[object Array]"==c.call(f)},a=function(f,a){if(f)for(var b=0;b<f.length;)a(f[b++])},r=function(f,a){for(var b in a)f[b]=a[b];return f},k=function(f,a){return r(Error(f),{src:"dojoLoader",info:a})},e=1,D=function(){return"_"+e++},p=function(f,a,b){return Sa(f,a,b,0,p)},w=this,x=w.document,
A=x&&x.createElement("DiV"),s=p.has=function(f){return n(u[f])?u[f]=u[f](w,x,A):u[f]},u=s.cache=q.hasCache;s.add=function(f,a,b,c){(void 0===u[f]||c)&&(u[f]=a);return b&&s(f)};for(var t in d.has)s.add(t,d.has[t],0,1);var v=0,I=[],y=0,X=m,P=m,V;p.isXdUrl=m;p.initSyncLoader=function(f,a,b){y||(y=f,X=a,P=b);return{sync:"sync",requested:1,arrived:2,nonmodule:3,executing:4,executed:5,syncExecStack:I,modules:G,execQ:M,getModule:S,injectModule:sa,setArrived:ba,signal:z,finishExec:ga,execModule:la,dojoRequirePlugin:y,
getLegacyMode:function(){return v},guardCheckComplete:ma}};var Q=location.protocol,R=location.host;p.isXdUrl=function(f){return/^\./.test(f)?!1:/^\/\//.test(f)?!0:(f=f.match(/^([^\/\:]+\:)\/+([^\/]+)/))&&(f[1]!=Q||R&&f[2]!=R)};s.add("dojo-force-activex-xhr",!x.addEventListener&&"file:"==window.location.protocol);s.add("native-xhr","undefined"!=typeof XMLHttpRequest);if(s("native-xhr")&&!s("dojo-force-activex-xhr"))V=function(){return new XMLHttpRequest};else{var ha=["Msxml2.XMLHTTP","Microsoft.XMLHTTP",
"Msxml2.XMLHTTP.4.0"],Y;for(g=0;3>g;)try{if(Y=ha[g++],new ActiveXObject(Y))break}catch(na){}V=function(){return new ActiveXObject(Y)}}p.getXhr=V;s.add("dojo-gettext-api",1);p.getText=function(f,a,b){var c=V();c.open("GET",ta(f),!1);c.send(null);if(200==c.status||!location.host&&!c.status)b&&b(c.responseText,a);else throw k("xhrFailed",c.status);return c.responseText};var ia=new Function("return eval(arguments[0]);");p.eval=function(f,a){return ia(f+"\r\n//# sourceURL\x3d"+a)};var B={},z=p.signal=
function(f,c){var k=B[f];a(k&&k.slice(0),function(f){f.apply(null,b(c)?c:[c])})},C=p.on=function(f,a){var b=B[f]||(B[f]=[]);b.push(a);return{remove:function(){for(var f=0;f<b.length;f++)if(b[f]===a){b.splice(f,1);break}}}},Z=[],N={},E=[],F={},ca=p.map={},J=[],G={},K="",L={},T={},ja={},U=0,H=function(f){var a,b,c,k;for(a in T)b=T[a],(c=a.match(/^url\:(.+)/))?L["url:"+Ta(c[1],f)]=b:"*now"==a?k=b:"*noref"!=a&&(c=oa(a,f,!0),L[c.mid]=L["url:"+c.url]=b);k&&k(Fa(f));T={}},$=function(f){return f.replace(/([\.$?*|{}\(\)\[\]\\\/\+^])/g,
function(f){return"\\"+f})},Ga=function(f,a){a.splice(0,a.length);for(var b in f)a.push([b,f[b],RegExp("^"+$(b)+"(/|$)"),b.length]);a.sort(function(f,a){return a[3]-f[3]});return a},fb=function(f,b){a(f,function(f){b.push([l(f[0])?RegExp("^"+$(f[0])+"$"):f[0],f[1]])})},Ua=function(f){var a=f.name;a||(a=f,f={name:a});f=r({main:"main"},f);f.location=f.location?f.location:a;f.packageMap&&(ca[a]=f.packageMap);f.main.indexOf("./")||(f.main=f.main.substring(2));F[a]=f},Va=[],pa=function(f,b,c){for(var k in f){"waitSeconds"==
k&&(p.waitms=1E3*(f[k]||0));"cacheBust"==k&&(K=f[k]?l(f[k])?f[k]:(new Date).getTime()+"":"");if("baseUrl"==k||"combo"==k)p[k]=f[k];if("async"==k){var e=f[k];p.legacyMode=v=l(e)&&/sync|legacyAsync/.test(e)?e:e?!1:"sync";p.async=!v}f[k]!==u&&(p.rawConfig[k]=f[k],"has"!=k&&s.add("config-"+k,f[k],0,b))}p.baseUrl||(p.baseUrl="./");/\/$/.test(p.baseUrl)||(p.baseUrl+="/");for(k in f.has)s.add(k,f.has[k],0,b);a(f.packages,Ua);for(var y in f.packagePaths)a(f.packagePaths[y],function(f){var a=y+"/"+f;l(f)&&
(f={name:f});f.location=a;Ua(f)});Ga(r(ca,f.map),J);a(J,function(f){f[1]=Ga(f[1],[]);"*"==f[0]&&(J.star=f)});Ga(r(N,f.paths),E);fb(f.aliases,Z);if(b)Va.push({config:f.config});else for(k in f.config)b=S(k,c),b.config=r(b.config||{},f.config[k]);f.cache&&(H(),T=f.cache,f.cache["*noref"]&&H());z("config",[f,p.rawConfig])};s("dojo-cdn");var ua=x.getElementsByTagName("script");g=0;for(var W,da,va,qa;g<ua.length;)if(W=ua[g++],(va=W.getAttribute("src"))&&(qa=va.match(/(((.*)\/)|^)dojo\.js(\W|$)/i))&&(da=
qa[3]||"",q.baseUrl=q.baseUrl||da,U=W),va=W.getAttribute("data-dojo-config")||W.getAttribute("djConfig"))ja=p.eval("({ "+va+" })","data-dojo-config"),U=W;p.rawConfig={};pa(q,1);s("dojo-cdn")&&((F.dojo.location=da)&&(da+="/"),F.dijit.location=da+"../dijit/",F.dojox.location=da+"../dojox/");pa(d,1);pa(ja,1);p.combo=p.combo||{add:m};var Ha=0,wa=[],Ia=null,ka=function(f){ma(function(){a(f.deps,sa);Ha&&!Ia&&(Ia=setTimeout(function(){Ha=0;Ia=null;p.combo.done(function(f,a){wa.push(f);ea=f;p.injectUrl(a,
function(){Ja(0,f);fa()},f);ea=0},p)},0))})},Sa=function(f,a,c,e,y){var H;if(l(f)){if((H=S(f,e,!0))&&H.executed)return H.result;throw k("undefinedModule",f);}b(f)||(pa(f,0,e),f=a,a=c);if(b(f))if(f.length){c="require*"+D();for(var g,h=[],d=0;d<f.length;)g=f[d++],h.push(S(g,e));H=r(xa("",c,0,""),{injected:2,deps:h,def:a||m,require:e?e.require:p,gc:1});G[H.mid]=H;ka(H);var $=ra&&"sync"!=v;ma(function(){la(H,$)});H.executed||M.push(H);fa()}else a&&a();return y},Fa=function(f){if(!f)return p;var a=f.require;
a||(a=function(b,k,c){return Sa(b,k,c,f,a)},f.require=r(a,p),a.module=f,a.toUrl=function(a){return Ta(a,f)},a.toAbsMid=function(a){return Ka(a,f)},a.syncLoadNls=function(a){a=oa(a,f);var b=G[a.mid];if(!b||!b.executed)if(aa=L[a.mid]||L["url:"+a.url])ya(aa),b=G[a.mid];return b&&b.executed&&b.result});return a},M=[],za=[],O={},gb=function(f){f.injected=1;O[f.mid]=1;f.url&&(O[f.url]=f.pack||1);Wa()},ba=function(f){f.injected=2;delete O[f.mid];f.url&&delete O[f.url];h(O)&&(Aa(),"xd"==v&&(v="sync"))},hb=
p.idle=function(){return!za.length&&h(O)&&!M.length&&!ra},La=function(f,a){if(a)for(var b=0;b<a.length;b++)if(a[b][2].test(f))return a[b];return 0},Xa=function(f){var a=[],b,k;for(f=f.replace(/\\/g,"/").split("/");f.length;)b=f.shift(),".."==b&&a.length&&".."!=k?(a.pop(),k=a[a.length-1]):"."!=b&&a.push(k=b);return a.join("/")},xa=function(f,a,b,k){var c=p.isXdUrl(k);return{pid:f,mid:a,pack:b,url:k,executed:0,def:0,isXd:c,isAmd:!!(c||F[f]&&F[f].isAmd)}},Ya=function(f,b,c,e,y,H,r,g,h){var p,d,l,$;$=
/^\./.test(f);if(/(^\/)|(\:)|(\.js$)/.test(f)||$&&!b)return xa(0,f,0,f);f=Xa($?b.mid+"/../"+f:f);if(/^\./.test(f))throw k("irrationalPath",f);b&&(l=La(b.mid,H));(l=(l=l||H.star)&&La(f,l[1]))&&(f=l[1]+f.substring(l[3]));b=(qa=f.match(/^([^\/]+)(\/(.+))?$/))?qa[1]:"";(p=c[b])?f=b+"/"+(d=qa[3]||p.main):b="";var m=0;a(g,function(a){var b=f.match(a[0]);b&&0<b.length&&(m=n(a[1])?f.replace(a[0],a[1]):a[1])});if(m)return Ya(m,0,c,e,y,H,r,g,h);if(c=e[f])return h?xa(c.pid,c.mid,c.pack,c.url):e[f];e=(l=La(f,
r))?l[1]+f.substring(l[3]):b?p.location+"/"+d:s("config-tlmSiblingOfDojo")?"../"+f:f;/(^\/)|(\:)/.test(e)||(e=y+e);return xa(b,f,p,Xa(e+".js"))},oa=function(f,a,b){return Ya(f,a,F,G,p.baseUrl,b?[]:J,b?[]:E,b?[]:Z)},Za=function(f,a,b){return f.normalize?f.normalize(a,function(f){return Ka(f,b)}):Ka(a,b)},$a=0,S=function(f,a,b){var k,c;(k=f.match(/^(.+?)\!(.*)$/))?(c=S(k[1],a,b),"sync"!=v||c.executed||(sa(c),2!==c.injected||c.executed||ma(function(){la(c)}),c.executed?Ba(c):M.unshift(c)),5!==c.executed||
c.load||Ba(c),c.load?(k=Za(c,k[2],a),f=c.mid+"!"+(c.dynamic?++$a+"!":"")+k):(k=k[2],f=c.mid+"!"+ ++$a+"!waitingForPlugin"),f={plugin:c,mid:f,req:Fa(a),prid:k}):f=oa(f,a);return G[f.mid]||!b&&(G[f.mid]=f)},Ka=p.toAbsMid=function(f,a){return oa(f,a).mid},Ta=p.toUrl=function(f,a){var b=oa(f+"/x",a),c=b.url;return ta(0===b.pid?f:c.substring(0,c.length-5))},ab={injected:2,executed:5,def:3,result:3},Ma=function(f){return G[f]=r({mid:f},ab)},ib=Ma("require"),jb=Ma("exports"),kb=Ma("module"),Ca={},Na=0,Ba=
function(f){var a=f.result;f.dynamic=a.dynamic;f.normalize=a.normalize;f.load=a.load;return f},lb=function(f){var b={};a(f.loadQ,function(a){var c=Za(f,a.prid,a.req.module),k=f.dynamic?a.mid.replace(/waitingForPlugin$/,c):f.mid+"!"+c,c=r(r({},a),{mid:k,prid:c,injected:0});G[k]||bb(G[k]=c);b[a.mid]=G[k];ba(a);delete G[a.mid]});f.loadQ=0;var c=function(f){for(var a=f.deps||[],c=0;c<a.length;c++)(f=b[a[c].mid])&&(a[c]=f)},k;for(k in G)c(G[k]);a(M,c)},ga=function(f){p.trace("loader-finish-exec",[f.mid]);
f.executed=5;f.defOrder=Na++;a(f.provides,function(f){f()});f.loadQ&&(Ba(f),lb(f));for(g=0;g<M.length;)M[g]===f?M.splice(g,1):g++;/^require\*/.test(f.mid)&&delete G[f.mid]},mb=[],la=function(f,a){if(4===f.executed)return p.trace("loader-circular-dependency",[mb.concat(f.mid).join("-\x3e")]),!f.def||a?Ca:f.cjs&&f.cjs.exports;if(!f.executed){if(!f.def)return Ca;var b=f.mid,c=f.deps||[],e,y=[],H=0;for(f.executed=4;e=c[H++];){e=e===ib?Fa(f):e===jb?f.cjs.exports:e===kb?f.cjs:la(e,a);if(e===Ca)return f.executed=
0,p.trace("loader-exec-module",["abort",b]),Ca;y.push(e)}p.trace("loader-run-factory",[f.mid]);var b=f.def,r;I.unshift(f);if(s("config-dojo-loader-catches"))try{r=n(b)?b.apply(null,y):b}catch(l){z("error",f.result=k("factoryThrew",[f,l]))}else r=n(b)?b.apply(null,y):b;f.result=void 0===r&&f.cjs?f.cjs.exports:r;I.shift(f);ga(f)}return f.result},ra=0,ma=function(f){try{ra++,f()}finally{ra--}hb()&&z("idle",[])},fa=function(){ra||ma(function(){X();for(var f,a,b=0;b<M.length;)f=Na,a=M[b],la(a),f!=Na?(X(),
b=0):b++})};void 0===s("dojo-loader-eval-hint-url")&&s.add("dojo-loader-eval-hint-url",1);var ta=function(f){f+="";return f+(K?(/\?/.test(f)?"\x26":"?")+K:"")},bb=function(f){var a=f.plugin;5!==a.executed||a.load||Ba(a);var b=function(a){f.result=a;ba(f);ga(f);fa()};a.load?a.load(f.prid,f.req,b):a.loadQ?a.loadQ.push(f):(a.loadQ=[f],M.unshift(a),sa(a))},aa=0,ea=0,Oa=0,ya=function(f,a){s("config-stripStrict")&&(f=f.replace(/"use strict"/g,""));Oa=1;if(s("config-dojo-loader-catches"))try{f===aa?aa.call(null):
p.eval(f,s("dojo-loader-eval-hint-url")?a.url:a.mid)}catch(b){z("error",k("evalModuleThrew",a))}else f===aa?aa.call(null):p.eval(f,s("dojo-loader-eval-hint-url")?a.url:a.mid);Oa=0},sa=function(f){var b=f.mid,c=f.url;if(!(f.executed||f.injected||O[b]||f.url&&(f.pack&&O[f.url]===f.pack||1==O[f.url]))){gb(f);var e=0;f.plugin&&f.plugin.isCombo?(p.combo.add(f.plugin.mid,f.prid,0,p),e=1):f.plugin||(e=p.combo.add(0,f.mid,f.url,p));if(e)Ha=1;else if(f.plugin)bb(f);else{var y=function(){Ja(f);if(2!==f.injected){if(s("dojo-enforceDefine")){z("error",
k("noDefine",f));return}ba(f);r(f,ab);p.trace("loader-define-nonmodule",[f.url])}v?!I.length&&fa():fa()};if(aa=L[b]||L["url:"+f.url])p.trace("loader-inject",["cache",f.mid,c]),ya(aa,f),y();else{if(v)if(f.isXd)"sync"==v&&(v="xd");else if(!f.isAmd||"sync"==v){e=function(k){if("sync"==v){I.unshift(f);ya(k,f);I.shift();Ja(f);f.cjs||(ba(f),ga(f));if(f.finish){k=b+"*finish";var e=f.finish;delete f.finish;Pa(k,["dojo",("dojo/require!"+e.join(",")).replace(/\./g,"/")],function(f){a(e,function(a){f.require(a)})});
M.unshift(S(k))}y()}else(k=P(f,k))?(ya(k,f),y()):(ea=f,p.injectUrl(ta(c),y,f),ea=0)};p.trace("loader-inject",["xhr",f.mid,c,"sync"!=v]);if(s("config-dojo-loader-catches"))try{p.getText(c,"sync"!=v,e)}catch(H){z("error",k("xhrInjectFailed",[f,H]))}else p.getText(c,"sync"!=v,e);return}p.trace("loader-inject",["script",f.mid,c]);ea=f;p.injectUrl(ta(c),y,f);ea=0}}}},Da=function(f,a,b){p.trace("loader-define-module",[f.mid,a]);if(f.plugin&&f.plugin.isCombo)return f.result=n(b)?b():b,ba(f),ga(f),f;var c=
f.mid;if(2===f.injected)return z("error",k("multipleDefine",f)),f;r(f,{deps:a,def:b,cjs:{id:f.mid,uri:f.url,exports:f.result={},setExports:function(a){f.cjs.exports=a},config:function(){return f.config}}});for(var e=0;a[e];e++)a[e]=S(a[e],f);v&&!O[c]&&(ka(f),M.push(f),fa());ba(f);n(b)||a.length||(f.result=b,ga(f));return f},Ja=function(f,b){for(var c=[],k,e;za.length;)e=za.shift(),b&&(e[0]=b.shift()),k=e[0]&&S(e[0])||f,c.push([k,e[1],e[2]]);H(f);a(c,function(f){ka(Da.apply(null,f))})},Ea=0,Aa=m,Wa=
m,Aa=function(){Ea&&clearTimeout(Ea);Ea=0},Wa=function(){Aa();p.waitms&&(Ea=window.setTimeout(function(){Aa();z("error",k("timeout",O))},p.waitms))};s.add("ie-event-behavior",x.attachEvent&&"undefined"===typeof Windows&&("undefined"===typeof opera||"[object Opera]"!=opera.toString()));var Qa=function(f,a,b,c){if(s("ie-event-behavior"))return f.attachEvent(b,c),function(){f.detachEvent(b,c)};f.addEventListener(a,c,!1);return function(){f.removeEventListener(a,c,!1)}},nb=Qa(window,"load","onload",function(){p.pageLoaded=
1;"complete"!=x.readyState&&(x.readyState="complete");nb()}),ua=x.getElementsByTagName("script");for(g=0;!U;)/^dojo/.test((W=ua[g++])&&W.type)||(U=W);p.injectUrl=function(f,a,b){b=b.node=x.createElement("script");var c=Qa(b,"load","onreadystatechange",function(f){f=f||window.event;var b=f.target||f.srcElement;if("load"===f.type||/complete|loaded/.test(b.readyState))c(),e(),a&&a()}),e=Qa(b,"error","onerror",function(a){c();e();z("error",k("scriptError",[f,a]))});b.type="text/javascript";b.charset=
"utf-8";b.src=f;U.parentNode.insertBefore(b,U);return b};p.log=function(){try{for(var f=0;f<arguments.length;f++);}catch(a){}};p.trace=m;var Pa=function(f,a,c){var e=arguments.length,y=["require","exports","module"],r=[0,f,a];1==e?r=[0,n(f)?y:[],f]:2==e&&l(f)?r=[f,n(a)?y:[],a]:3==e&&(r=[f,a,c]);p.trace("loader-define",r.slice(0,2));if((e=r[0]&&S(r[0]))&&!O[e.mid])ka(Da(e,r[1],r[2]));else if(!s("ie-event-behavior")||Oa)za.push(r);else{e=e||ea;if(!e){for(f in O)if((y=G[f])&&y.node&&"interactive"===
y.node.readyState){e=y;break}if(!e)for(var g=0;g<wa.length;g++){e=wa[g];if(e.node&&"interactive"===e.node.readyState)break;e=0}}b(e)?(ka(Da(S(e.shift()),r[1],r[2])),e.length||wa.splice(g,1)):e?(H(e),ka(Da(e,r[1],r[2]))):z("error",k("ieDefineFailed",r[0]));fa()}};Pa.amd={vendor:"dojotoolkit.org"};r(r(p,q.loaderPatch),d.loaderPatch);C("error",function(f){try{if(f instanceof Error)for(var a in f);}catch(b){}});r(p,{uid:D,cache:L,packs:F});if(w.define)z("error",k("defineAlreadyDefined",0));else{w.define=
Pa;w.require=p;if(p.combo&&p.combo.plugins){var cb=p.combo.plugins,Ra;for(Ra in cb)r(r(S(Ra),cb[Ra]),{isCombo:1,executed:"executed",load:1})}a(Va,function(f){pa(f)});var db=ja.deps||d.deps||q.deps,eb=ja.callback||d.callback||q.callback;p.boot=db||eb?[db||[],eb]:0}})(this.dojoConfig||this.djConfig||this.require||{},{async:0,hasCache:{"config-selectorEngine":"acme","config-tlmSiblingOfDojo":1,"dojo-built":1,"dojo-loader":1,dom:1,"host-browser":1},packages:[{location:".",name:"dojo"},{location:"../js/dijit",
name:"dijit"},{location:"../js/dojox",name:"dojox"},{location:"../js/pi",name:"pi"},{location:"../js/lh",name:"lh"},{location:"../css",name:"css"},{location:"../img",name:"img"},{location:"../fonts",name:"fonts"},{location:"../js",name:"polyfills_ie.js"},{location:"../js",name:"polyfills_regular.js"},{location:"../js",name:"lh_jquery.js"},{location:"../js",name:"lh_jquery.min.js"},{location:"../js",name:"mmcore.js"},{location:"../js",name:"vendor.js"},{location:"../js",name:"vendor.min.js"},{location:"../js/edynamics",
name:"edynamics"}]});
require({cache:{"dojo/require":function(){define(["./_base/loader"],function(d){return{dynamic:0,normalize:function(d){return d},load:d.require}})},"dojo/_base/loader":function(){define("./kernel ../has require module ../json ./lang ./array".split(" "),function(d,q,g,m,h,c,n){var l=function(a){return a.replace(/\./g,"/")},b=/\/\/>>built/,a=[],r=[],k=function(b,c,k){a.push(k);n.forEach(b.split(","),function(a){a=R(a,c.module);r.push(a);ha(a)});e()},e=function(){var b,c;for(c in V)if(b=V[c],void 0===
b.noReqPluginCheck&&(b.noReqPluginCheck=/loadInit\!/.test(c)||/require\!/.test(c)?1:0),!b.executed&&!b.noReqPluginCheck&&b.injected==t)return;C(function(){var b=a;a=[];n.forEach(b,function(a){a(1)})})},D=function(a,b,c){var e=/\(|\)/g,k=1;for(e.lastIndex=b;(b=e.exec(a))&&(k=")"==b[0]?k-1:k+1,0!=k););if(0!=k)throw"unmatched paren around character "+e.lastIndex+" in: "+a;return[d.trim(a.substring(c,e.lastIndex))+";\n",e.lastIndex]},p=/(\/\*([\s\S]*?)\*\/|\/\/(.*)$)/mg,w=/(^|\s)dojo\.(loadInit|require|provide|requireLocalization|requireIf|requireAfterIf|platformRequire)\s*\(/mg,
x=/(^|\s)(require|define)\s*\(/m,A=function(a,b){var c,e,k,y=[],r=[];c=[];for(b=b||a.replace(p,function(a){w.lastIndex=x.lastIndex=0;return w.test(a)||x.test(a)?"":a});c=w.exec(b);)e=w.lastIndex,k=e-c[0].length,e=D(b,e,k),"loadInit"==c[2]?y.push(e[0]):r.push(e[0]),w.lastIndex=e[1];c=y.concat(r);return c.length||!x.test(b)?[a.replace(/(^|\s)dojo\.loadInit\s*\(/g,"\n0 \x26\x26 dojo.loadInit("),c.join(""),c]:0},s=g.initSyncLoader(k,e,function(a,c){var e,k,y=[],r=[];if(b.test(c)||!(e=A(c)))return 0;k=
a.mid+"-*loadInit";for(var g in R("dojo",a).result.scopeMap)y.push(g),r.push('"'+g+'"');return"// xdomain rewrite of "+a.mid+"\ndefine('"+k+"',{\n\tnames:"+h.stringify(y)+",\n\tdef:function("+y.join(",")+"){"+e[1]+"}});\n\ndefine("+h.stringify(y.concat(["dojo/loadInit!"+k]))+", function("+y.join(",")+"){\n"+e[0]+"});"}),u=s.sync,t=s.requested,v=s.arrived,I=s.nonmodule,y=s.executing,X=s.executed,P=s.syncExecStack,V=s.modules,Q=s.execQ,R=s.getModule,ha=s.injectModule,Y=s.setArrived,na=s.signal,ia=s.finishExec,
B=s.execModule,z=s.getLegacyMode,C=s.guardCheckComplete,k=s.dojoRequirePlugin;d.provide=function(a){var b=P[0],e=c.mixin(R(l(a),g.module),{executed:y,result:c.getObject(a,!0)});Y(e);b&&(b.provides||(b.provides=[])).push(function(){e.result=c.getObject(a);delete e.provides;e.executed!==X&&ia(e)});return e.result};q.add("config-publishRequireResult",1,0,0);d.require=function(a,b){var e=function(a,b){var c=R(l(a),g.module);if(P.length&&P[0].finish)P[0].finish.push(a);else{if(c.executed)return c.result;
b&&(c.result=I);var e=z();ha(c);e=z();c.executed!==X&&c.injected===v&&s.guardCheckComplete(function(){B(c)});if(c.executed)return c.result;e==u?c.cjs?Q.unshift(c):P.length&&(P[0].finish=[a]):Q.push(c)}}(a,b);q("config-publishRequireResult")&&!c.exists(a)&&void 0!==e&&c.setObject(a,e);return e};d.loadInit=function(a){a()};d.registerModulePath=function(a,b){var c={};c[a.replace(/\./g,"/")]=b;g({paths:c})};d.platformRequire=function(a){a=(a.common||[]).concat(a[d._name]||a["default"]||[]);for(var b;a.length;)c.isArray(b=
a.shift())?d.require.apply(d,b):d.require(b)};d.requireIf=d.requireAfterIf=function(a,b,c){a&&d.require(b,c)};d.requireLocalization=function(a,b,c){g(["../i18n"],function(e){e.getLocalization(a,b,c)})};return{extractLegacyApiApplications:A,require:k,loadInit:function(a,b,c){b([a],function(a){b(a.names,function(){for(var e="",y=[],r=0;r<arguments.length;r++)e+="var "+a.names[r]+"\x3d arguments["+r+"]; ",y.push(arguments[r]);eval(e);var g=b.module,h=[],p,e={provide:function(a){a=l(a);a=R(a,g);a!==g&&
Y(a)},require:function(a,b){a=l(a);b&&(R(a,g).result=I);h.push(a)},requireLocalization:function(a,b,c){p||(p=["dojo/i18n"]);c=(c||d.locale).toLowerCase();a=l(a)+"/nls/"+(/root/i.test(c)?"":c+"/")+l(b);R(a,g).isXd&&p.push("dojo/i18n!"+a)},loadInit:function(a){a()}},r={},n;try{for(n in e)r[n]=d[n],d[n]=e[n];a.def.apply(null,y)}catch(D){na("error",[{src:m.id,id:"failedDojoLoadInit"},D])}finally{for(n in e)d[n]=r[n]}p&&(h=h.concat(p));h.length?k(h.join(","),b,c):c()})})}}})},"dojo/_base/kernel":function(){define(["../has",
"./config","require","module"],function(d,q,g,m){var h,c;h=function(){return this}();var n={},l={},b={config:q,global:h,dijit:n,dojox:l},n={dojo:["dojo",b],dijit:["dijit",n],dojox:["dojox",l]};m=g.map&&g.map[m.id.match(/[^\/]+/)[0]];for(c in m)n[c]?n[c][0]=m[c]:n[c]=[m[c],{}];for(c in n)m=n[c],m[1]._scopeName=m[0],q.noGlobals||(h[m[0]]=m[1]);b.scopeMap=n;b.baseUrl=b.config.baseUrl=g.baseUrl;b.isAsync=g.async;b.locale=q.locale;h="$Rev: 2dfbbaf $".match(/[0-9a-f]{7,}/);b.version={major:1,minor:9,patch:7,
flag:"build20160502-2356,1.9.7-20130926-IBM",revision:h?h[0]:NaN,toString:function(){var a=b.version;return a.major+"."+a.minor+"."+a.patch+a.flag+" ("+a.revision+")"}};Function("d","d.eval \x3d function(){return d.global.eval ? d.global.eval(arguments[0]) : eval(arguments[0]);}")(b);b.exit=function(){};"undefined"!=typeof console||(console={});m="assert count debug dir dirxml error group groupEnd info profile profileEnd time timeEnd trace warn log".split(" ");var a;for(h=0;a=m[h++];)console[a]||
function(){var b=a+"";console[b]="log"in console?function(){var a=Array.prototype.slice.call(arguments);a.unshift(b+":");console.log(a.join(" "))}:function(){};console[b]._fake=!0}();d.add("dojo-debug-messages",!!q.isDebug);b.deprecated=b.experimental=function(){};d("dojo-debug-messages")&&(b.deprecated=function(a,b,c){},b.experimental=function(a,b){});if(q.modulePaths){b.deprecated("dojo.modulePaths","use paths configuration");d={};for(c in q.modulePaths)d[c.replace(/\./g,"/")]=q.modulePaths[c];
g({paths:d})}b.moduleUrl=function(a,c){b.deprecated("dojo.moduleUrl()","use require.toUrl","2.0");var e=null;a&&(e=g.toUrl(a.replace(/\./g,"/")+(c?"/"+c:"")+"/*.*").replace(/\/\*\.\*/,"")+(c?"":"/"));return e};b._hasResource={};return b})},"dojo/has":function(){define(["require","module"],function(d,q){var g=d.has||function(){};g.add("dom-addeventlistener",!!document.addEventListener);g.add("touch","ontouchstart"in document||0<window.navigator.msMaxTouchPoints);g.add("device-width",screen.availWidth||
innerWidth);var m=document.createElement("form");g.add("dom-attributes-explicit",0==m.attributes.length);g.add("dom-attributes-specified-flag",0<m.attributes.length&&40>m.attributes.length);g.clearElement=function(g){g.innerHTML="";return g};g.normalize=function(h,c){var d=h.match(/[\?:]|[^:\?]*/g),l=0,b=function(a){var c=d[l++];if(":"==c)return 0;if("?"==d[l++]){if(!a&&g(c))return b();b(!0);return b(a)}return c||0};return(h=b())&&c(h)};g.load=function(g,c,d){g?c([g],d):d()};return g})},"dojo/_base/config":function(){define(["../has",
"require"],function(d,q){var g={},m=q.rawConfig,h;for(h in m)g[h]=m[h];g.locale||"undefined"==typeof navigator||(g.locale=(navigator.language||navigator.userLanguage).toLowerCase());return g})},"dojo/json":function(){define(["./has"],function(d){var q="undefined"!=typeof JSON;d.add("json-parse",q);d.add("json-stringify",q&&'{"a":1}'==JSON.stringify({a:0},function(g,d){return d||1}));if(d("json-stringify"))return JSON;var g=function(g){return('"'+g.replace(/(["\\])/g,"\\$1")+'"').replace(/[\f]/g,"\\f").replace(/[\b]/g,
"\\b").replace(/[\n]/g,"\\n").replace(/[\t]/g,"\\t").replace(/[\r]/g,"\\r")};return{parse:d("json-parse")?JSON.parse:function(g,d){if(d&&!/^([\s\[\{]*(?:"(?:\\.|[^"])*"|-?\d[\d\.]*(?:[Ee][+-]?\d+)?|null|true|false|)[\s\]\}]*(?:,|:|$))+$/.test(g))throw new SyntaxError("Invalid characters in JSON");return eval("("+g+")")},stringify:function(d,h,c){function n(b,a,r){h&&(b=h(r,b));var k;k=typeof b;if("number"==k)return isFinite(b)?b+"":"null";if("boolean"==k)return b+"";if(null===b)return"null";if("string"==
typeof b)return g(b);if("function"==k||"undefined"==k)return l;if("function"==typeof b.toJSON)return n(b.toJSON(r),a,r);if(b instanceof Date)return'"{FullYear}-{Month+}-{Date}T{Hours}:{Minutes}:{Seconds}Z"'.replace(/\{(\w+)(\+)?\}/g,function(a,c,e){a=b["getUTC"+c]()+(e?1:0);return 10>a?"0"+a:a});if(b.valueOf()!==b)return n(b.valueOf(),a,r);var e=c?a+c:"",d=c?" ":"",p=c?"\n":"";if(b instanceof Array){var d=b.length,m=[];for(r=0;r<d;r++)k=n(b[r],e,r),"string"!=typeof k&&(k="null"),m.push(p+e+k);return"["+
m.join(",")+p+a+"]"}m=[];for(r in b){var q;if(b.hasOwnProperty(r)){if("number"==typeof r)q='"'+r+'"';else if("string"==typeof r)q=g(r);else continue;k=n(b[r],e,r);"string"==typeof k&&m.push(p+e+q+":"+d+k)}}return"{"+m.join(",")+p+a+"}"}var l;"string"==typeof h&&(c=h,h=null);return n(d,"","")}}})},"dojo/_base/lang":function(){define(["./kernel","../has","../sniff"],function(d,q){q.add("bug-for-in-skips-shadowed",function(){for(var a in{toString:1})return 0;return 1});var g=q("bug-for-in-skips-shadowed")?
"hasOwnProperty valueOf isPrototypeOf propertyIsEnumerable toLocaleString toString constructor".split(" "):[],m=g.length,h=function(a,b,c){var e,g=0,p=d.global;if(!c)if(a.length){e=a[g++];try{c=d.scopeMap[e]&&d.scopeMap[e][1]}catch(l){}c=c||(e in p?p[e]:b?p[e]={}:void 0)}else return p;for(;c&&(e=a[g++]);)c=e in c?c[e]:b?c[e]={}:void 0;return c},c=Object.prototype.toString,n=function(a,b,c){return(c||[]).concat(Array.prototype.slice.call(a,b||0))},l=/\{([^\}]+)\}/g,b={_extraNames:g,_mixin:function(a,
b,c){var e,d,p,l={};for(e in b)d=b[e],e in a&&(a[e]===d||e in l&&l[e]===d)||(a[e]=c?c(d):d);if(q("bug-for-in-skips-shadowed")&&b)for(p=0;p<m;++p)e=g[p],d=b[e],e in a&&(a[e]===d||e in l&&l[e]===d)||(a[e]=c?c(d):d);return a},mixin:function(a,c){a||(a={});for(var k=1,e=arguments.length;k<e;k++)b._mixin(a,arguments[k]);return a},setObject:function(a,b,c){var e=a.split(".");a=e.pop();return(c=h(e,!0,c))&&a?c[a]=b:void 0},getObject:function(a,b,c){return h(a.split("."),b,c)},exists:function(a,c){return void 0!==
b.getObject(a,!1,c)},isString:function(a){return"string"==typeof a||a instanceof String},isArray:function(a){return a&&(a instanceof Array||"array"==typeof a)},isFunction:function(a){return"[object Function]"===c.call(a)},isObject:function(a){return void 0!==a&&(null===a||"object"==typeof a||b.isArray(a)||b.isFunction(a))},isArrayLike:function(a){return a&&void 0!==a&&!b.isString(a)&&!b.isFunction(a)&&!(a.tagName&&"form"==a.tagName.toLowerCase())&&(b.isArray(a)||isFinite(a.length))},isAlien:function(a){return a&&
!b.isFunction(a)&&/\{\s*\[native code\]\s*\}/.test(String(a))},extend:function(a,c){for(var k=1,e=arguments.length;k<e;k++)b._mixin(a.prototype,arguments[k]);return a},_hitchArgs:function(a,c){var k=b._toArray(arguments,2),e=b.isString(c);return function(){var g=b._toArray(arguments),l=e?(a||d.global)[c]:c;return l&&l.apply(a||this,k.concat(g))}},hitch:function(a,c){if(2<arguments.length)return b._hitchArgs.apply(d,arguments);c||(c=a,a=null);if(b.isString(c)){a=a||d.global;if(!a[c])throw['lang.hitch: scope["',
c,'"] is null (scope\x3d"',a,'")'].join("");return function(){return a[c].apply(a,arguments||[])}}return a?function(){return c.apply(a,arguments||[])}:c},delegate:function(){function a(){}return function(c,k){a.prototype=c;var e=new a;a.prototype=null;k&&b._mixin(e,k);return e}}(),_toArray:q("ie")?function(){function a(a,b,c){c=c||[];for(b=b||0;b<a.length;b++)c.push(a[b]);return c}return function(b){return(b.item?a:n).apply(this,arguments)}}():n,partial:function(a){return b.hitch.apply(d,[null].concat(b._toArray(arguments)))},
clone:function(a){if(!a||"object"!=typeof a||b.isFunction(a))return a;if(a.nodeType&&"cloneNode"in a)return a.cloneNode(!0);if(a instanceof Date)return new Date(a.getTime());if(a instanceof RegExp)return RegExp(a);var c,k,e;if(b.isArray(a))for(c=[],k=0,e=a.length;k<e;++k)k in a&&c.push(b.clone(a[k]));else c=a.constructor?new a.constructor:{};return b._mixin(c,a,b.clone)},trim:String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^\s\s*/,"").replace(/\s\s*$/,"")},replace:function(a,
c,k){return a.replace(k||l,b.isFunction(c)?c:function(a,k){return b.getObject(k,!1,c)})}};b.mixin(d,b);return b})},"dojo/sniff":function(){define(["./has"],function(d){var q=navigator,g=q.userAgent,q=q.appVersion,m=parseFloat(q);d.add("air",0<=g.indexOf("AdobeAIR"));d.add("msapp",parseFloat(g.split("MSAppHost/")[1])||void 0);d.add("khtml",0<=q.indexOf("Konqueror")?m:void 0);d.add("webkit",parseFloat(g.split("WebKit/")[1])||void 0);d.add("chrome",parseFloat(g.split("Chrome/")[1])||void 0);d.add("safari",
0<=q.indexOf("Safari")&&!d("chrome")?parseFloat(q.split("Version/")[1]):void 0);d.add("mac",0<=q.indexOf("Macintosh"));d.add("quirks","BackCompat"==document.compatMode);if(g.match(/(iPhone|iPod|iPad)/)){var h=RegExp.$1.replace(/P/,"p"),c=g.match(/OS ([\d_]+)/)?RegExp.$1:"1",c=parseFloat(c.replace(/_/,".").replace(/_/g,""));d.add(h,c);d.add("ios",c)}d.add("android",parseFloat(g.split("Android ")[1])||void 0);d.add("bb",(0<=g.indexOf("BlackBerry")||0<=g.indexOf("BB10"))&&parseFloat(g.split("Version/")[1])||
void 0);d.add("trident",parseFloat(q.split("Trident/")[1])||void 0);d.add("svg","undefined"!==typeof SVGAngle);d("webkit")||(0<=g.indexOf("Opera")&&d.add("opera",9.8<=m?parseFloat(g.split("Version/")[1])||m:m),0<=g.indexOf("Gecko")&&!d("khtml")&&!d("webkit")&&!d("trident")&&d.add("mozilla",m),d("mozilla")&&d.add("ff",parseFloat(g.split("Firefox/")[1]||g.split("Minefield/")[1])||void 0),document.all&&!d("opera")&&(g=parseFloat(q.split("MSIE ")[1])||void 0,(q=document.documentMode)&&5!=q&&Math.floor(g)!=
q&&(g=q),d.add("ie",g)),d.add("wii","undefined"!=typeof opera&&opera.wiiremote));return d})},"dojo/_base/array":function(){define(["./kernel","../has","./lang"],function(d,q,g){function m(a){return n[a]=new Function("item","index","array",a)}function h(a){var b=!a;return function(c,e,g){var d=0,l=c&&c.length||0,h;l&&"string"==typeof c&&(c=c.split(""));"string"==typeof e&&(e=n[e]||m(e));if(g)for(;d<l;++d){if(h=!e.call(g,c[d],d,c),a^h)return!h}else for(;d<l;++d)if(h=!e(c[d],d,c),a^h)return!h;return b}}
function c(a){var c=1,k=0,e=0;a||(c=k=e=-1);return function(d,g,h,m){if(m&&0<c)return b.lastIndexOf(d,g,h);m=d&&d.length||0;var n=a?m+e:k;h===l?h=a?k:m+e:0>h?(h=m+h,0>h&&(h=k)):h=h>=m?m+e:h;for(m&&"string"==typeof d&&(d=d.split(""));h!=n;h+=c)if(d[h]==g)return h;return-1}}var n={},l,b={every:h(!1),some:h(!0),indexOf:c(!0),lastIndexOf:c(!1),forEach:function(a,b,c){var e=0,d=a&&a.length||0;d&&"string"==typeof a&&(a=a.split(""));"string"==typeof b&&(b=n[b]||m(b));if(c)for(;e<d;++e)b.call(c,a[e],e,a);
else for(;e<d;++e)b(a[e],e,a)},map:function(a,b,c,e){var d=0,g=a&&a.length||0;e=new (e||Array)(g);g&&"string"==typeof a&&(a=a.split(""));"string"==typeof b&&(b=n[b]||m(b));if(c)for(;d<g;++d)e[d]=b.call(c,a[d],d,a);else for(;d<g;++d)e[d]=b(a[d],d,a);return e},filter:function(a,b,c){var e=0,d=a&&a.length||0,g=[],h;d&&"string"==typeof a&&(a=a.split(""));"string"==typeof b&&(b=n[b]||m(b));if(c)for(;e<d;++e)h=a[e],b.call(c,h,e,a)&&g.push(h);else for(;e<d;++e)h=a[e],b(h,e,a)&&g.push(h);return g},clearCache:function(){n=
{}}};g.mixin(d,b);return b})},"dojo/parser":function(){define("require ./_base/kernel ./_base/lang ./_base/array ./_base/config ./dom ./_base/window ./_base/url ./aspect ./promise/all ./date/stamp ./Deferred ./has ./query ./on ./ready".split(" "),function(d,q,g,m,h,c,n,l,b,a,r,k,e,D,p,w){function x(a){return eval("("+a+")")}function A(a){var b=a._nameCaseMap,c=a.prototype;if(!b||b._extendCnt<u){var b=a._nameCaseMap={},e;for(e in c)"_"!==e.charAt(0)&&(b[e.toLowerCase()]=e);b._extendCnt=u}return b}
function s(a,b){var c=a.join();if(!t[c]){for(var e=[],k=0,h=a.length;k<h;k++){var l=a[k];e[e.length]=t[l]=t[l]||g.getObject(l)||~l.indexOf("/")&&(b?b(l):d(l))}k=e.shift();t[c]=e.length?k.createSubclass?k.createSubclass(e):k.extend.apply(k,e):k}return t[c]}new Date("X");var u=0;b.after(g,"extend",function(){u++},!0);var t={},v={_clearCache:function(){u++;t={}},_functionFromScript:function(a,b){var c="",e="",d=a.getAttribute(b+"args")||a.getAttribute("args"),k=a.getAttribute("with"),d=(d||"").split(/\s*,\s*/);
k&&k.length&&m.forEach(k.split(/\s*,\s*/),function(a){c+="with("+a+"){";e+="}"});return new Function(d,c+a.innerHTML+e)},instantiate:function(a,b,c){b=b||{};c=c||{};var e=(c.scope||q._scopeName)+"Type",d="data-"+(c.scope||q._scopeName)+"-",k=d+"type",g=d+"mixins",h=[];m.forEach(a,function(a){var c=e in b?b[e]:a.getAttribute(k)||a.getAttribute(e);if(c){var d=a.getAttribute(g),c=d?[c].concat(d.split(/\s*,\s*/)):[c];h.push({node:a,types:c})}});return this._instantiate(h,b,c)},_instantiate:function(b,
c,e,d){function k(a){c._started||e.noStart||m.forEach(a,function(a){"function"!==typeof a.startup||a._started||a.startup()});return a}b=m.map(b,function(a){var b=a.ctor||s(a.types,e.contextRequire);if(!b)throw Error("Unable to resolve constructor for: '"+a.types.join()+"'");return this.construct(b,a.node,c,e,a.scripts,a.inherited)},this);return d?a(b).then(k):k(b)},construct:function(a,c,d,k,h,n){function s(a){Z&&g.setObject(Z,a);for(z=0;z<J.length;z++)b[J[z].advice||"after"](a,J[z].method,g.hitch(a,
J[z].func),!0);for(z=0;z<G.length;z++)G[z].call(a);for(z=0;z<K.length;z++)a.watch(K[z].prop,K[z].func);for(z=0;z<L.length;z++)p(a,L[z].event,L[z].func);return a}var u=a&&a.prototype;k=k||{};var t={};k.defaults&&g.mixin(t,k.defaults);n&&g.mixin(t,n);var w;e("dom-attributes-explicit")?w=c.attributes:e("dom-attributes-specified-flag")?w=m.filter(c.attributes,function(a){return a.specified}):(n=(/^input$|^img$/i.test(c.nodeName)?c:c.cloneNode(!1)).outerHTML.replace(/=[^\s"']+|="[^"]*"|='[^']*'/g,"").replace(/^\s*<[a-zA-Z0-9]*\s*/,
"").replace(/\s*>.*$/,""),w=m.map(n.split(/\s+/),function(a){var b=a.toLowerCase();return{name:a,value:"LI"==c.nodeName&&"value"==a||"enctype"==b?c.getAttribute(b):c.getAttributeNode(b).value}}));var v=k.scope||q._scopeName;n="data-"+v+"-";var B={};"dojo"!==v&&(B[n+"props"]="data-dojo-props",B[n+"type"]="data-dojo-type",B[n+"mixins"]="data-dojo-mixins",B[v+"type"]="dojoType",B[n+"id"]="data-dojo-id");for(var z=0,C,v=[],Z,N;C=w[z++];){var E=C.name,F=E.toLowerCase();C=C.value;switch(B[F]||F){case "data-dojo-type":case "dojotype":case "data-dojo-mixins":break;
case "data-dojo-props":N=C;break;case "data-dojo-id":case "jsid":Z=C;break;case "data-dojo-attach-point":case "dojoattachpoint":t.dojoAttachPoint=C;break;case "data-dojo-attach-event":case "dojoattachevent":t.dojoAttachEvent=C;break;case "class":t["class"]=c.className;break;case "style":t.style=c.style&&c.style.cssText;break;default:if(E in u||(E=A(a)[F]||E),E in u)switch(typeof u[E]){case "string":t[E]=C;break;case "number":t[E]=C.length?Number(C):NaN;break;case "boolean":t[E]="false"!=C.toLowerCase();
break;case "function":""===C||-1!=C.search(/[^\w\.]+/i)?t[E]=new Function(C):t[E]=g.getObject(C,!1)||new Function(C);v.push(E);break;default:F=u[E],t[E]=F&&"length"in F?C?C.split(/\s*,\s*/):[]:F instanceof Date?""==C?new Date(""):"now"==C?new Date:r.fromISOString(C):F instanceof l?q.baseUrl+C:x(C)}else t[E]=C}}for(w=0;w<v.length;w++)B=v[w].toLowerCase(),c.removeAttribute(B),c[B]=null;if(N)try{N=x.call(k.propsThis,"{"+N+"}"),g.mixin(t,N)}catch(ca){throw Error(ca.toString()+" in data-dojo-props\x3d'"+
N+"'");}g.mixin(t,d);h||(h=a&&(a._noScript||u._noScript)?[]:D("\x3e script[type^\x3d'dojo/']",c));var J=[],G=[],K=[],L=[];if(h)for(z=0;z<h.length;z++)B=h[z],c.removeChild(B),d=B.getAttribute(n+"event")||B.getAttribute("event"),k=B.getAttribute(n+"prop"),N=B.getAttribute(n+"method"),v=B.getAttribute(n+"advice"),w=B.getAttribute("type"),B=this._functionFromScript(B,n),d?"dojo/connect"==w?J.push({method:d,func:B}):"dojo/on"==w?L.push({event:d,func:B}):t[d]=B:"dojo/aspect"==w?J.push({method:N,advice:v,
func:B}):"dojo/watch"==w?K.push({prop:k,func:B}):G.push(B);a=(h=a.markupFactory||u.markupFactory)?h(t,c,a):new a(t,c);return a.then?a.then(s):s(a)},scan:function(a,b){function c(a){if(!a.inherited){a.inherited={};var b=a.node,e=c(a.parent),b={dir:b.getAttribute("dir")||e.dir,lang:b.getAttribute("lang")||e.lang,textDir:b.getAttribute(D)||e.textDir},d;for(d in b)b[d]&&(a.inherited[d]=b[d])}return a.inherited}var g=[],h=[],l={},n=(b.scope||q._scopeName)+"Type",p="data-"+(b.scope||q._scopeName)+"-",r=
p+"type",D=p+"textdir",p=p+"mixins",t=a.firstChild,u=b.inherited;if(!u){var w=function(a,b){return a.getAttribute&&a.getAttribute(b)||a.parentNode&&w(a.parentNode,b)},u={dir:w(a,"dir"),lang:w(a,"lang"),textDir:w(a,D)},x;for(x in u)u[x]||delete u[x]}for(var u={inherited:u},v,A;;)if(t)if(1!=t.nodeType)t=t.nextSibling;else if(v&&"script"==t.nodeName.toLowerCase())(E=t.getAttribute("type"))&&/^dojo\/\w/i.test(E)&&v.push(t),t=t.nextSibling;else if(A)t=t.nextSibling;else{var E=t.getAttribute(r)||t.getAttribute(n);
x=t.firstChild;if(E||x&&(3!=x.nodeType||x.nextSibling)){A=null;if(E){var F=t.getAttribute(p);v=F?[E].concat(F.split(/\s*,\s*/)):[E];try{A=s(v,b.contextRequire)}catch(ca){}A||m.forEach(v,function(a){~a.indexOf("/")&&!l[a]&&(l[a]=!0,h[h.length]=a)});F=A&&!A.prototype._noScript?[]:null;u={types:v,ctor:A,parent:u,node:t,scripts:F};u.inherited=c(u);g.push(u)}else u={node:t,scripts:v,parent:u};v=F;A=t.stopParser||A&&A.prototype.stopParser&&!b.template;t=x}else t=t.nextSibling}else{if(!u||!u.node)break;
t=u.node.nextSibling;A=!1;u=u.parent;v=u.scripts}var J=new k;h.length?(e("dojo-debug-messages"),(b.contextRequire||d)(h,function(){J.resolve(m.filter(g,function(a){if(!a.ctor)try{a.ctor=s(a.types,b.contextRequire)}catch(c){}for(var e=a.parent;e&&!e.types;)e=e.parent;var d=a.ctor&&a.ctor.prototype;a.instantiateChildren=!(d&&d.stopParser&&!b.template);a.instantiate=!e||e.instantiate&&e.instantiateChildren;return a.instantiate}))})):J.resolve(g);return J.promise},_require:function(a,b){var c=x("{"+a.innerHTML+
"}"),e=[],h=[],l=new k,p=b&&b.contextRequire||d,n;for(n in c)e.push(n),h.push(c[n]);p(h,function(){for(var a=0;a<e.length;a++)g.setObject(e[a],arguments[a]);l.resolve(arguments)});return l.promise},_scanAmd:function(a,b){var c=new k,e=c.promise;c.resolve(!0);var d=this;D("script[type\x3d'dojo/require']",a).forEach(function(a){e=e.then(function(){return d._require(a,b)});a.parentNode.removeChild(a)});return e},parse:function(a,b){var e;!b&&a&&a.rootNode?(b=a,e=b.rootNode):!a||!g.isObject(a)||"nodeType"in
a?e=a:b=a;e=e?c.byId(e):n.body();b=b||{};var d=b.template?{template:!0}:{},k=[],h=this,l=this._scanAmd(e,b).then(function(){return h.scan(e,b)}).then(function(a){return h._instantiate(a,d,b,!0)}).then(function(a){return k=k.concat(a)}).otherwise(function(a){throw a;});g.mixin(k,l);return k}};q.parser=v;h.parseOnLoad&&w(100,v,"parse");return v})},"dojo/dom":function(){define(["./sniff","./_base/window"],function(d,q){if(7>=d("ie"))try{document.execCommand("BackgroundImageCache",!1,!0)}catch(g){}var m=
{};d("ie")?m.byId=function(c,d){if("string"!=typeof c)return c;var g=d||q.doc,b=c&&g.getElementById(c);if(!b||b.attributes.id.value!=c&&b.id!=c){g=g.all[c];if(!g||g.nodeName)g=[g];for(var a=0;b=g[a++];)if(b.attributes&&b.attributes.id&&b.attributes.id.value==c||b.id==c)return b}else return b}:m.byId=function(c,d){return("string"==typeof c?(d||q.doc).getElementById(c):c)||null};m.isDescendant=function(c,d){try{for(c=m.byId(c),d=m.byId(d);c;){if(c==d)return!0;c=c.parentNode}}catch(g){}return!1};d.add("css-user-select",
function(c,d,g){if(!g)return!1;c=g.style;d=["Khtml","O","Moz","Webkit"];g=d.length;var b="userSelect";do if("undefined"!==typeof c[b])return b;while(g--&&(b=d[g]+"UserSelect"));return!1});var h=d("css-user-select");m.setSelectable=h?function(c,d){m.byId(c).style[h]=d?"":"none"}:function(c,d){c=m.byId(c);var g=c.getElementsByTagName("*"),b=g.length;if(d)for(c.removeAttribute("unselectable");b--;)g[b].removeAttribute("unselectable");else for(c.setAttribute("unselectable","on");b--;)g[b].setAttribute("unselectable",
"on")};return m})},"dojo/_base/window":function(){define(["./kernel","./lang","../sniff"],function(d,q,g){var m={global:d.global,doc:d.global.document||null,body:function(g){g=g||d.doc;return g.body||g.getElementsByTagName("body")[0]},setContext:function(g,c){d.global=m.global=g;d.doc=m.doc=c},withGlobal:function(g,c,n,l){var b=d.global;try{return d.global=m.global=g,m.withDoc.call(null,g.document,c,n,l)}finally{d.global=m.global=b}},withDoc:function(h,c,n,l){var b=m.doc,a=g("quirks"),r=g("ie"),k,
e,q;try{return d.doc=m.doc=h,d.isQuirks=g.add("quirks","BackCompat"==d.doc.compatMode,!0,!0),g("ie")&&(q=h.parentWindow)&&q.navigator&&(k=parseFloat(q.navigator.appVersion.split("MSIE ")[1])||void 0,(e=h.documentMode)&&5!=e&&Math.floor(k)!=e&&(k=e),d.isIE=g.add("ie",k,!0,!0)),n&&"string"==typeof c&&(c=n[c]),c.apply(n,l||[])}finally{d.doc=m.doc=b,d.isQuirks=g.add("quirks",a,!0,!0),d.isIE=g.add("ie",r,!0,!0)}}};q.mixin(d,m);return m})},"dojo/_base/url":function(){define(["./kernel"],function(d){var q=
/^(([^:/?#]+):)?(\/\/([^/?#]*))?([^?#]*)(\?([^#]*))?(#(.*))?$/,g=/^((([^\[:]+):)?([^@]+)@)?(\[([^\]]+)\]|([^\[:]*))(:([0-9]+))?$/,m=function(){for(var d=arguments,c=[d[0]],n=1;n<d.length;n++)if(d[n]){var l=new m(d[n]+""),c=new m(c[0]+"");if(""==l.path&&!l.scheme&&!l.authority&&!l.query)null!=l.fragment&&(c.fragment=l.fragment),l=c;else if(!l.scheme&&(l.scheme=c.scheme,!l.authority&&(l.authority=c.authority,"/"!=l.path.charAt(0)))){for(var c=(c.path.substring(0,c.path.lastIndexOf("/")+1)+l.path).split("/"),
b=0;b<c.length;b++)"."==c[b]?b==c.length-1?c[b]="":(c.splice(b,1),b--):0<b&&(1!=b||""!=c[0])&&".."==c[b]&&".."!=c[b-1]&&(b==c.length-1?(c.splice(b,1),c[b-1]=""):(c.splice(b-1,2),b-=2));l.path=c.join("/")}c=[];l.scheme&&c.push(l.scheme,":");l.authority&&c.push("//",l.authority);c.push(l.path);l.query&&c.push("?",l.query);l.fragment&&c.push("#",l.fragment)}this.uri=c.join("");d=this.uri.match(q);this.scheme=d[2]||(d[1]?"":null);this.authority=d[4]||(d[3]?"":null);this.path=d[5];this.query=d[7]||(d[6]?
"":null);this.fragment=d[9]||(d[8]?"":null);null!=this.authority&&(d=this.authority.match(g),this.user=d[3]||null,this.password=d[4]||null,this.host=d[6]||d[7],this.port=d[9]||null)};m.prototype.toString=function(){return this.uri};return d._Url=m})},"dojo/aspect":function(){define([],function(){function d(c,b,a,d){var g=c[b],e="around"==b,h;if(e){var p=a(function(){return g.advice(this,arguments)});h={remove:function(){p&&(p=c=a=null)},advice:function(a,b){return p?p.apply(a,b):g.advice(a,b)}}}else h=
{remove:function(){if(h.advice){var e=h.previous,d=h.next;d||e?(e?e.next=d:c[b]=d,d&&(d.previous=e)):delete c[b];c=a=h.advice=null}},id:m++,advice:a,receiveArguments:d};if(g&&!e)if("after"==b){for(;g.next&&(g=g.next););g.next=h;h.previous=g}else"before"==b&&(c[b]=h,h.next=g,g.previous=h);else c[b]=h;return h}function q(c){return function(b,a,h,k){var e=b[a],n;e&&e.target==b||(b[a]=n=function(){for(var a=m,b=arguments,c=n.before;c;)b=c.advice.apply(this,b)||b,c=c.next;if(n.around)var e=n.around.advice(this,
b);for(c=n.after;c&&c.id<a;){if(c.receiveArguments)var d=c.advice.apply(this,b),e=d===g?e:d;else e=c.advice.call(this,e,b);c=c.next}return e},e&&(n.around={advice:function(a,b){return e.apply(a,b)}}),n.target=b);b=d(n||e,c,h,k);h=null;return b}}var g,m=0,h=q("after"),c=q("before"),n=q("around");return{before:c,around:n,after:h}})},"dojo/promise/all":function(){define(["../_base/array","../Deferred","../when"],function(d,q,g){var m=d.some;return function(d){var c,n;d instanceof Array?n=d:d&&"object"===
typeof d&&(c=d);var l,b=[];if(c){n=[];for(var a in c)Object.hasOwnProperty.call(c,a)&&(b.push(a),n.push(c[a]));l={}}else n&&(l=[]);if(!n||!n.length)return(new q).resolve(l);var r=new q;r.promise.always(function(){l=b=null});var k=n.length;m(n,function(a,d){c||b.push(d);g(a,function(a){r.isFulfilled()||(l[b[d]]=a,0===--k&&r.resolve(l))},r.reject);return r.isFulfilled()});return r.promise}})},"dojo/Deferred":function(){define(["./has","./_base/lang","./errors/CancelError","./promise/Promise","./promise/instrumentation"],
function(d,q,g,m,h){var c=Object.freeze||function(){},n=function(a,b,c,d,g){2===b&&r.instrumentRejected&&0===a.length&&r.instrumentRejected(c,!1,d,g);for(g=0;g<a.length;g++)l(a[g],b,c,d)},l=function(c,e,d,g){var h=c[e],l=c.deferred;if(h)try{var n=h(d);if(0===e)"undefined"!==typeof n&&a(l,e,n);else{if(n&&"function"===typeof n.then){c.cancel=n.cancel;n.then(b(l,1),b(l,2),b(l,0));return}a(l,1,n)}}catch(m){a(l,2,m)}else a(l,e,d);2===e&&r.instrumentRejected&&r.instrumentRejected(d,!!h,g,l.promise)},b=
function(b,c){return function(d){a(b,c,d)}},a=function(a,b,c){if(!a.isCanceled())switch(b){case 0:a.progress(c);break;case 1:a.resolve(c);break;case 2:a.reject(c)}},r=function(a){var b=this.promise=new m,d=this,h,q,x,A=!1,s=[];Error.captureStackTrace&&(Error.captureStackTrace(d,r),Error.captureStackTrace(b,r));this.isResolved=b.isResolved=function(){return 1===h};this.isRejected=b.isRejected=function(){return 2===h};this.isFulfilled=b.isFulfilled=function(){return!!h};this.isCanceled=b.isCanceled=
function(){return A};this.progress=function(a,c){if(h){if(!0===c)throw Error("This deferred has already been fulfilled.");return b}n(s,0,a,null,d);return b};this.resolve=function(a,c){if(h){if(!0===c)throw Error("This deferred has already been fulfilled.");return b}n(s,h=1,q=a,null,d);s=null;return b};var u=this.reject=function(a,c){if(h){if(!0===c)throw Error("This deferred has already been fulfilled.");return b}Error.captureStackTrace&&Error.captureStackTrace(x={},u);n(s,h=2,q=a,x,d);s=null;return b};
this.then=b.then=function(a,c,d){var g=[d,a,c];g.cancel=b.cancel;g.deferred=new r(function(a){return g.cancel&&g.cancel(a)});h&&!s?l(g,h,q,x):s.push(g);return g.deferred.promise};this.cancel=b.cancel=function(b,c){if(!h){if(a){var d=a(b);b="undefined"===typeof d?b:d}A=!0;if(!h)return"undefined"===typeof b&&(b=new g),u(b),b;if(2===h&&q===b)return b}else if(!0===c)throw Error("This deferred has already been fulfilled.");};c(b)};r.prototype.toString=function(){return"[object Deferred]"};h&&h(r);return r})},
"dojo/errors/CancelError":function(){define(["./create"],function(d){return d("CancelError",null,null,{dojoType:"cancel"})})},"dojo/errors/create":function(){define(["../_base/lang"],function(d){return function(q,g,m,h){m=m||Error;var c=function(d){if(m===Error){Error.captureStackTrace&&Error.captureStackTrace(this,c);var h=Error.call(this,d),b;for(b in h)h.hasOwnProperty(b)&&(this[b]=h[b]);this.message=d;this.stack=h.stack}else m.apply(this,arguments);g&&g.apply(this,arguments)};c.prototype=d.delegate(m.prototype,
h);c.prototype.name=q;return c.prototype.constructor=c}})},"dojo/promise/Promise":function(){define(["../_base/lang"],function(d){function q(){throw new TypeError("abstract");}return d.extend(function(){},{then:function(d,m,h){q()},cancel:function(d,m){q()},isResolved:function(){q()},isRejected:function(){q()},isFulfilled:function(){q()},isCanceled:function(){q()},always:function(d){return this.then(d,d)},otherwise:function(d){return this.then(null,d)},trace:function(){return this},traceRejected:function(){return this},
toString:function(){return"[object Promise]"}})})},"dojo/promise/instrumentation":function(){define(["./tracer","../has","../_base/lang","../_base/array"],function(d,q,g,m){function h(a,b,c){b&&b.stack&&b.stack.split("\n").slice(1).join("\n").replace(/^\s+/," ")}function c(a,b,c,d){b||h(a,c,d)}function n(c,d,g,h){m.some(b,function(a){if(a.error===c)return d&&(a.handled=!0),!0})||b.push({error:c,rejection:g,handled:d,deferred:h,timestamp:(new Date).getTime()});a||(a=setTimeout(l,r))}function l(){var c=
(new Date).getTime(),d=c-r;b=m.filter(b,function(a){return a.timestamp<d?(a.handled||h(a.error,a.rejection,a.deferred),!1):!0});a=b.length?setTimeout(l,b[0].timestamp+r-c):!1}q.add("config-useDeferredInstrumentation","report-unhandled-rejections");var b=[],a=!1,r=1E3;return function(a){var b=q("config-useDeferredInstrumentation");if(b){d.on("resolved",g.hitch(console,"log","resolved"));d.on("rejected",g.hitch(console,"log","rejected"));d.on("progress",g.hitch(console,"log","progress"));var h=[];"string"===
typeof b&&(h=b.split(","),b=h.shift());if("report-rejections"===b)a.instrumentRejected=c;else if("report-unhandled-rejections"===b||!0===b||1===b)a.instrumentRejected=n,r=parseInt(h[0],10)||r;else throw Error("Unsupported instrumentation usage \x3c"+b+"\x3e");}}})},"dojo/promise/tracer":function(){define(["../_base/lang","./Promise","../Evented"],function(d,q,g){function m(d){setTimeout(function(){c.apply(h,d)},0)}var h=new g,c=h.emit;h.emit=null;q.prototype.trace=function(){var c=d._toArray(arguments);
this.then(function(d){m(["resolved",d].concat(c))},function(d){m(["rejected",d].concat(c))},function(d){m(["progress",d].concat(c))});return this};q.prototype.traceRejected=function(){var c=d._toArray(arguments);this.otherwise(function(d){m(["rejected",d].concat(c))});return this};return h})},"dojo/Evented":function(){define(["./aspect","./on"],function(d,q){function g(){}var m=d.after;g.prototype={on:function(d,c){return q.parse(this,d,c,function(d,g){return m(d,"on"+g,c,!0)})},emit:function(d,c){var g=
[this];g.push.apply(g,arguments);return q.emit.apply(q,g)}};return g})},"dojo/on":function(){define(["./has!dom-addeventlistener?:./aspect","./_base/kernel","./sniff"],function(d,q,g){function m(a,c,d,e,h){if(e=c.match(/(.*):(.*)/))return c=e[2],e=e[1],l.selector(e,c).call(h,a,d);g("touch")&&(b.test(c)&&(d=I(d)),g("event-orientationchange")||"orientationchange"!=c||(c="resize",a=window,d=I(d)));D&&(d=D(d));if(a.addEventListener){var m=c in k,n=m?k[c]:c;a.addEventListener(n,d,m);return{remove:function(){a.removeEventListener(n,
d,m)}}}if(A&&a.attachEvent)return A(a,"on"+c,d);throw Error("Target must be an event emitter");}function h(){this.cancelable=!1;this.defaultPrevented=!0}function c(){this.bubbles=!1}var n=window.ScriptEngineMajorVersion;g.add("jscript",n&&n()+ScriptEngineMinorVersion()/10);g.add("event-orientationchange",g("touch")&&!g("android"));g.add("event-stopimmediatepropagation",window.Event&&!!window.Event.prototype&&!!window.Event.prototype.stopImmediatePropagation);g.add("event-focusin",function(a,b,c){return"onfocusin"in
c});g("touch")&&g.add("touch-can-modify-event-delegate",function(){var a=function(){};a.prototype=document.createEvent("MouseEvents");try{var b=new a;b.target=null;return null===b.target}catch(c){return!1}});var l=function(a,b,c,d){return"function"!=typeof a.on||"function"==typeof b||a.nodeType?l.parse(a,b,c,m,d,this):a.on(b,c)};l.pausable=function(a,b,c,d){var e;a=l(a,b,function(){if(!e)return c.apply(this,arguments)},d);a.pause=function(){e=!0};a.resume=function(){e=!1};return a};l.once=function(a,
b,c,d){var e=l(a,b,function(){e.remove();return c.apply(this,arguments)});return e};l.parse=function(a,b,c,d,e,g){if(b.call)return b.call(g,a,c);if(-1<b.indexOf(",")){b=b.split(/\s*,\s*/);for(var h=[],k=0,l;l=b[k++];)h.push(d(a,l,c,e,g));h.remove=function(){for(var a=0;a<h.length;a++)h[a].remove()};return h}return d(a,b,c,e,g)};var b=/^touch/;l.selector=function(a,b,c){return function(d,e){function g(b){for(h=h&&h.matches?h:q.query;!h.matches(b,a,d);)if(b==d||!1===c||!(b=b.parentNode)||1!=b.nodeType)return;
return b}var h="function"==typeof a?{matches:a}:this,k=b.bubble;return k?l(d,k(g),e):l(d,b,function(a){var b=g(a.target);if(b)return e.call(b,a)})}};var a=[].slice,r=l.emit=function(b,d,e){var g=a.call(arguments,2),k="on"+d;if("parentNode"in b){var l=g[0]={},m;for(m in e)l[m]=e[m];l.preventDefault=h;l.stopPropagation=c;l.target=b;l.type=d;e=l}do b[k]&&b[k].apply(b,g);while(e&&e.bubbles&&(b=b.parentNode));return e&&e.cancelable&&e},k=g("event-focusin")?{}:{focusin:"focus",focusout:"blur"};if(!g("event-stopimmediatepropagation"))var e=
function(){this.modified=this.immediatelyStopped=!0},D=function(a){return function(b){if(!b.immediatelyStopped)return b.stopImmediatePropagation=e,a.apply(this,arguments)}};if(g("dom-addeventlistener"))l.emit=function(a,b,c){if(a.dispatchEvent&&document.createEvent){var d=(a.ownerDocument||document).createEvent("HTMLEvents");d.initEvent(b,!!c.bubbles,!!c.cancelable);for(var e in c)e in d||(d[e]=c[e]);return a.dispatchEvent(d)&&d}return r.apply(l,arguments)};else{l._fixEvent=function(a,b){a||(a=(b&&
(b.ownerDocument||b.document||b).parentWindow||window).event);if(!a)return a;try{p&&a.type==p.type&&a.srcElement==p.target&&(a=p)}catch(c){}if(!a.target)switch(a.target=a.srcElement,a.currentTarget=b||a.srcElement,"mouseover"==a.type&&(a.relatedTarget=a.fromElement),"mouseout"==a.type&&(a.relatedTarget=a.toElement),a.stopPropagation||(a.stopPropagation=s,a.preventDefault=u),a.type){case "keypress":var d="charCode"in a?a.charCode:a.keyCode;10==d?(d=0,a.keyCode=13):13==d||27==d?d=0:3==d&&(d=99);a.charCode=
d;d=a;d.keyChar=d.charCode?String.fromCharCode(d.charCode):"";d.charOrCode=d.keyChar||d.keyCode}return a};var p,w=function(a){this.handle=a};w.prototype.remove=function(){delete _dojoIEListeners_[this.handle]};var x=function(a){return function(b){b=l._fixEvent(b,this);var c=a.call(this,b);b.modified&&(p||setTimeout(function(){p=null}),p=b);return c}},A=function(a,b,c){c=x(c);if(((a.ownerDocument?a.ownerDocument.parentWindow:a.parentWindow||a.window||window)!=top||5.8>g("jscript"))&&!g("config-_allow_leaks")){"undefined"==
typeof _dojoIEListeners_&&(_dojoIEListeners_=[]);var e=a[b];if(!e||!e.listeners){var h=e,e=Function("event","var callee \x3d arguments.callee; for(var i \x3d 0; i\x3ccallee.listeners.length; i++){var listener \x3d _dojoIEListeners_[callee.listeners[i]]; if(listener){listener.call(this,event);}}");e.listeners=[];a[b]=e;e.global=this;h&&e.listeners.push(_dojoIEListeners_.push(h)-1)}e.listeners.push(a=e.global._dojoIEListeners_.push(c)-1);return new w(a)}return d.after(a,b,c,!0)},s=function(){this.cancelBubble=
!0},u=l._preventDefault=function(){this.bubbledKeyCode=this.keyCode;if(this.ctrlKey)try{this.keyCode=0}catch(a){}this.defaultPrevented=!0;this.returnValue=!1;this.modified=!0}}if(g("touch"))var t=function(){},v=window.orientation,I=function(a){return function(b){var c=b.corrected;if(!c){var d=b.type;try{delete b.type}catch(e){}if(b.type){if(g("touch-can-modify-event-delegate"))t.prototype=b,c=new t;else{var c={},h;for(h in b)c[h]=b[h]}c.preventDefault=function(){b.preventDefault()};c.stopPropagation=
function(){b.stopPropagation()}}else c=b,c.type=d;b.corrected=c;if("resize"==d){if(v==window.orientation)return null;v=window.orientation;c.type="orientationchange";return a.call(this,c)}"rotation"in c||(c.rotation=0,c.scale=1);var d=c.changedTouches[0],k;for(k in d)delete c[k],c[k]=d[k]}return a.call(this,c)}};return l})},"dojo/when":function(){define(["./Deferred","./promise/Promise"],function(d,q){return function(g,m,h,c){var n=g&&"function"===typeof g.then,l=n&&g instanceof q;if(!n)return 1<arguments.length?
m?m(g):g:(new d).resolve(g);l||(n=new d(g.cancel),g.then(n.resolve,n.reject,n.progress),g=n.promise);return m||h||c?g.then(m,h,c):g}})},"dojo/date/stamp":function(){define(["../_base/lang","../_base/array"],function(d,q){var g={};d.setObject("dojo.date.stamp",g);g.fromISOString=function(d,h){g._isoRegExp||(g._isoRegExp=/^(?:(\d{4})(?:-(\d{2})(?:-(\d{2}))?)?)?(?:T(\d{2}):(\d{2})(?::(\d{2})(.\d+)?)?((?:[+-](\d{2}):(\d{2}))|Z)?)?$/);var c=g._isoRegExp.exec(d),n=null;if(c){c.shift();c[1]&&c[1]--;c[6]&&
(c[6]*=1E3);h&&(h=new Date(h),q.forEach(q.map("FullYear Month Date Hours Minutes Seconds Milliseconds".split(" "),function(a){return h["get"+a]()}),function(a,b){c[b]=c[b]||a}));n=new Date(c[0]||1970,c[1]||0,c[2]||1,c[3]||0,c[4]||0,c[5]||0,c[6]||0);100>c[0]&&n.setFullYear(c[0]||1970);var l=0,b=c[7]&&c[7].charAt(0);"Z"!=b&&(l=60*(c[8]||0)+(Number(c[9])||0),"-"!=b&&(l*=-1));b&&(l-=n.getTimezoneOffset());l&&n.setTime(n.getTime()+6E4*l)}return n};g.toISOString=function(d,g){var c=function(a){return 10>
a?"0"+a:a};g=g||{};var n=[],l=g.zulu?"getUTC":"get",b="";"time"!=g.selector&&(b=d[l+"FullYear"](),b=["0000".substr((b+"").length)+b,c(d[l+"Month"]()+1),c(d[l+"Date"]())].join("-"));n.push(b);if("date"!=g.selector){b=[c(d[l+"Hours"]()),c(d[l+"Minutes"]()),c(d[l+"Seconds"]())].join(":");l=d[l+"Milliseconds"]();g.milliseconds&&(b+="."+(100>l?"0":"")+c(l));if(g.zulu)b+="Z";else if("time"!=g.selector)var l=d.getTimezoneOffset(),a=Math.abs(l),b=b+((0<l?"-":"+")+c(Math.floor(a/60))+":"+c(a%60));n.push(b)}return n.join("T")};
return g})},"dojo/query":function(){define("./_base/kernel ./has ./dom ./on ./_base/array ./_base/lang ./selector/_loader ./selector/_loader!default".split(" "),function(d,q,g,m,h,c,n,l){function b(a,b){var c=function(c,d){if("string"==typeof d&&(d=g.byId(d),!d))return new b([]);var e="string"==typeof c?a(c,d):c?c.end&&c.on?c:[c]:[];return e.end&&e.on?e:new b(e)};c.matches=a.match||function(a,b,d){return 0<c.filter([a],b,d).length};c.filter=a.filter||function(a,b,d){return c(b,d).filter(function(b){return-1<
h.indexOf(a,b)})};if("function"!=typeof a){var d=a.search;a=function(a,b){return d(b||document,a)}}return c}q.add("array-extensible",function(){return 1==c.delegate([],{length:1}).length&&!q("bug-for-in-skips-shadowed")});var a=Array.prototype,r=a.slice,k=a.concat,e=h.forEach,D=function(a,b,c){b=[0].concat(r.call(b,0));c=c||d.global;return function(d){b[0]=d;return a.apply(c,b)}},p=function(a){var b=this instanceof w&&q("array-extensible");"number"==typeof a&&(a=Array(a));var d=a&&"length"in a?a:
arguments;if(b||!d.sort){for(var e=b?this:[],g=e.length=d.length,h=0;h<g;h++)e[h]=d[h];if(b)return e;d=e}c._mixin(d,x);d._NodeListCtor=function(a){return w(a)};return d},w=p,x=w.prototype=q("array-extensible")?[]:{};w._wrap=x._wrap=function(a,b,c){a=new (c||this._NodeListCtor||w)(a);return b?a._stash(b):a};w._adaptAsMap=function(a,b){return function(){return this.map(D(a,arguments,b))}};w._adaptAsForEach=function(a,b){return function(){this.forEach(D(a,arguments,b));return this}};w._adaptAsFilter=
function(a,b){return function(){return this.filter(D(a,arguments,b))}};w._adaptWithCondition=function(a,b,c){return function(){var e=arguments,g=D(a,e,c);if(b.call(c||d.global,e))return this.map(g);this.forEach(g);return this}};e(["slice","splice"],function(b){var c=a[b];x[b]=function(){return this._wrap(c.apply(this,arguments),"slice"==b?this:null)}});e(["indexOf","lastIndexOf","every","some"],function(a){var b=h[a];x[a]=function(){return b.apply(d,[this].concat(r.call(arguments,0)))}});c.extend(p,
{constructor:w,_NodeListCtor:w,toString:function(){return this.join(",")},_stash:function(a){this._parent=a;return this},on:function(a,b){var c=this.map(function(c){return m(c,a,b)});c.remove=function(){for(var a=0;a<c.length;a++)c[a].remove()};return c},end:function(){return this._parent?this._parent:new this._NodeListCtor(0)},concat:function(a){var b=r.call(this,0),c=h.map(arguments,function(a){return r.call(a,0)});return this._wrap(k.apply(b,c),this)},map:function(a,b){return this._wrap(h.map(this,
a,b),this)},forEach:function(a,b){e(this,a,b);return this},filter:function(a){var b=arguments,c=this,d=0;if("string"==typeof a){c=A._filterResult(this,b[0]);if(1==b.length)return c._stash(this);d=1}return this._wrap(h.filter(c,b[d],b[d+1]),this)},instantiate:function(a,b){var d=c.isFunction(a)?a:c.getObject(a);b=b||{};return this.forEach(function(a){new d(b,a)})},at:function(){var a=new this._NodeListCtor(0);e(arguments,function(b){0>b&&(b=this.length+b);this[b]&&a.push(this[b])},this);return a._stash(this)}});
var A=b(l,p);d.query=b(l,function(a){return p(a)});A.load=function(a,c,d){n.load(a,c,function(a){d(b(a,p))})};d._filterQueryResult=A._filterResult=function(a,b,c){return new p(A.filter(a,b,c))};d.NodeList=A.NodeList=p;return A})},"dojo/selector/_loader":function(){define(["../has","require"],function(d,q){var g=document.createElement("div");d.add("dom-qsa2.1",!!g.querySelectorAll);d.add("dom-qsa3",function(){try{return g.innerHTML="\x3cp class\x3d'TEST'\x3e\x3c/p\x3e",1==g.querySelectorAll(".TEST:empty").length}catch(d){}});
var m;return{load:function(g,c,n,l){l=q;g="default"==g?d("config-selectorEngine")||"css3":g;g="css2"==g||"lite"==g?"./lite":"css2.1"==g?d("dom-qsa2.1")?"./lite":"./acme":"css3"==g?d("dom-qsa3")?"./lite":"./acme":"acme"==g?"./acme":(l=c)&&g;if("?"==g.charAt(g.length-1)){g=g.substring(0,g.length-1);var b=!0}if(b&&(d("dom-compliant-qsa")||m))return n(m);l([g],function(a){"./lite"!=g&&(m=a);n(a)})}}})},"dojo/selector/acme":function(){define(["../dom","../sniff","../_base/array","../_base/lang","../_base/window"],
function(d,q,g,m,h){var c=m.trim,n=g.forEach,l="BackCompat"==h.doc.compatMode,b=!1,a=function(){return!0},r=function(a){a=0<="\x3e~+".indexOf(a.slice(-1))?a+" * ":a+" ";for(var d=function(b,d){return c(a.slice(b,d))},e=[],g=-1,h=-1,k=-1,l=-1,n=-1,m=-1,p=-1,q,r="",s="",x,t=0,w=a.length,u=null,v=null,A=function(){0<=m&&(u.id=d(m,t).replace(/\\/g,""),m=-1);if(0<=p){var a=p==t?null:d(p,t);u[0>"\x3e~+".indexOf(a)?"tag":"oper"]=a;p=-1}0<=n&&(u.classes.push(d(n+1,t).replace(/\\/g,"")),n=-1)};r=s,s=a.charAt(t),
t<w;t++)"\\"!=r&&(u||(x=t,u={query:null,pseudos:[],attrs:[],classes:[],tag:null,oper:null,id:null,getTag:function(){return b?this.otag:this.tag}},p=t),q?s==q&&(q=null):"'"==s||'"'==s?q=s:0<=g?"]"==s?(v.attr?v.matchFor=d(k||g+1,t):v.attr=d(g+1,t),!(g=v.matchFor)||'"'!=g.charAt(0)&&"'"!=g.charAt(0)||(v.matchFor=g.slice(1,-1)),v.matchFor&&(v.matchFor=v.matchFor.replace(/\\/g,"")),u.attrs.push(v),v=null,g=k=-1):"\x3d"==s&&(k=0<="|~^$*".indexOf(r)?r:"",v.type=k+s,v.attr=d(g+1,t-k.length),k=t+1):0<=h?")"==
s&&(0<=l&&(v.value=d(h+1,t)),l=h=-1):"#"==s?(A(),m=t+1):"."==s?(A(),n=t):":"==s?(A(),l=t):"["==s?(A(),g=t,v={}):"("==s?(0<=l&&(v={name:d(l+1,t),value:null},u.pseudos.push(v)),h=t):" "==s&&r!=s&&(A(),0<=l&&u.pseudos.push({name:d(l+1,t)}),u.loops=u.pseudos.length||u.attrs.length||u.classes.length,u.oquery=u.query=d(x,t),u.otag=u.tag=u.oper?null:u.tag||"*",u.tag&&(u.tag=u.tag.toUpperCase()),e.length&&e[e.length-1].oper&&(u.infixOper=e.pop(),u.query=u.infixOper.query+" "+u.query),e.push(u),u=null));return e},
k=function(a,b){return a?b?function(){return a.apply(window,arguments)&&b.apply(window,arguments)}:a:b},e=function(a,b){var c=b||[];a&&c.push(a);return c},D=function(a){return 1==a.nodeType},p=function(a,c){return a?"class"==c?a.className||"":"for"==c?a.htmlFor||"":"style"==c?a.style.cssText||"":(b?a.getAttribute(c):a.getAttribute(c,2))||"":""},w={"*\x3d":function(a,b){return function(c){return 0<=p(c,a).indexOf(b)}},"^\x3d":function(a,b){return function(c){return 0==p(c,a).indexOf(b)}},"$\x3d":function(a,
b){return function(c){c=" "+p(c,a);var d=c.lastIndexOf(b);return-1<d&&d==c.length-b.length}},"~\x3d":function(a,b){var c=" "+b+" ";return function(b){return 0<=(" "+p(b,a)+" ").indexOf(c)}},"|\x3d":function(a,b){var c=b+"-";return function(d){d=p(d,a);return d==b||0==d.indexOf(c)}},"\x3d":function(a,b){return function(c){return p(c,a)==b}}},x="undefined"==typeof h.doc.firstChild.nextElementSibling,A=x?"nextSibling":"nextElementSibling",s=x?"previousSibling":"previousElementSibling",u=x?D:a,t=function(a){for(;a=
a[s];)if(u(a))return!1;return!0},v=function(a){for(;a=a[A];)if(u(a))return!1;return!0},I=function(a){var b=a.parentNode,b=7!=b.nodeType?b:b.nextSibling,c=0,d=b.children||b.childNodes,e=a._i||a.getAttribute("_i")||-1,g=b._l||("undefined"!==typeof b.getAttribute?b.getAttribute("_l"):-1);if(!d)return-1;d=d.length;if(g==d&&0<=e&&0<=g)return e;q("ie")&&"undefined"!==typeof b.setAttribute?b.setAttribute("_l",d):b._l=d;e=-1;for(b=b.firstElementChild||b.firstChild;b;b=b[A])u(b)&&(q("ie")?b.setAttribute("_i",
++c):b._i=++c,a===b&&(e=c));return e},y=function(a){return!(I(a)%2)},X=function(a){return I(a)%2},P={checked:function(a,b){return function(a){return!("checked"in a?!a.checked:!a.selected)}},disabled:function(a,b){return function(a){return a.disabled}},enabled:function(a,b){return function(a){return!a.disabled}},"first-child":function(){return t},"last-child":function(){return v},"only-child":function(a,b){return function(a){return t(a)&&v(a)}},empty:function(a,b){return function(a){var b=a.childNodes;
for(a=a.childNodes.length-1;0<=a;a--){var c=b[a].nodeType;if(1===c||3==c)return!1}return!0}},contains:function(a,b){var c=b.charAt(0);if('"'==c||"'"==c)b=b.slice(1,-1);return function(a){return 0<=a.innerHTML.indexOf(b)}},not:function(a,b){var c=r(b)[0],d={el:1};"*"!=c.tag&&(d.tag=1);c.classes.length||(d.classes=1);var e=Q(c,d);return function(a){return!e(a)}},"nth-child":function(a,b){var c=parseInt;if("odd"==b)return X;if("even"==b)return y;if(-1!=b.indexOf("n")){var d=b.split("n",2),e=d[0]?"-"==
d[0]?-1:c(d[0]):1,g=d[1]?c(d[1]):0,h=0,k=-1;0<e?0>g?g=g%e&&e+g%e:0<g&&(g>=e&&(h=g-g%e),g%=e):0>e&&(e*=-1,0<g&&(k=g,g%=e));if(0<e)return function(a){a=I(a);return a>=h&&(0>k||a<=k)&&a%e==g};b=g}var l=c(b);return function(a){return I(a)==l}}},V=9>q("ie")||9==q("ie")&&q("quirks")?function(a){var c=a.toLowerCase();"class"==c&&(a="className");return function(d){return b?d.getAttribute(a):d[a]||d[c]}}:function(a){return function(b){return b&&b.getAttribute&&b.hasAttribute(a)}},Q=function(c,d){if(!c)return a;
d=d||{};var e=null;"el"in d||(e=k(e,D));"tag"in d||"*"!=c.tag&&(e=k(e,function(a){return a&&(b?a.tagName:a.tagName.toUpperCase())==c.getTag()}));"classes"in d||n(c.classes,function(a,b,c){var d=RegExp("(?:^|\\s)"+a+"(?:\\s|$)");e=k(e,function(a){return d.test(a.className)});e.count=b});"pseudos"in d||n(c.pseudos,function(a){var b=a.name;P[b]&&(e=k(e,P[b](b,a.value)))});"attrs"in d||n(c.attrs,function(a){var b,c=a.attr;a.type&&w[a.type]?b=w[a.type](c,a.matchFor):c.length&&(b=V(c));b&&(e=k(e,b))});
"id"in d||c.id&&(e=k(e,function(a){return!!a&&a.id==c.id}));e||"default"in d||(e=a);return e},R=function(a){return function(b,c,d){for(;b=b[A];)if(!x||D(b)){d&&!T(b,d)||!a(b)||c.push(b);break}return c}},ha=function(a){return function(b,c,d){for(b=b[A];b;){if(u(b)){if(d&&!T(b,d))break;a(b)&&c.push(b)}b=b[A]}return c}},Y=function(b){b=b||a;return function(a,c,d){for(var e=0,g=a.children||a.childNodes;a=g[e++];)u(a)&&(!d||T(a,d))&&b(a,e)&&c.push(a);return c}},na={},ia=function(b){var c=na[b.query];if(c)return c;
var g=b.infixOper,g=g?g.oper:"",k=Q(b,{el:1}),n="*"==b.tag,m=h.doc.getElementsByClassName;if(g)m={el:1},n&&(m.tag=1),k=Q(b,m),"+"==g?c=R(k):"~"==g?c=ha(k):"\x3e"==g&&(c=Y(k));else if(b.id)k=!b.loops&&n?a:Q(b,{el:1,id:1}),c=function(a,c){var g=d.byId(b.id,a.ownerDocument||a);if(g&&k(g)){if(9==a.nodeType)return e(g,c);for(var h=g.parentNode;h&&h!=a;)h=h.parentNode;if(h)return e(g,c)}};else if(m&&/\{\s*\[native code\]\s*\}/.test(String(m))&&b.classes.length&&!l)var k=Q(b,{el:1,classes:1,id:1}),p=b.classes.join(" "),
c=function(a,b,c){b=e(0,b);for(var d,g=0,h=a.getElementsByClassName(p);d=h[g++];)k(d,a)&&T(d,c)&&b.push(d);return b};else n||b.loops?(k=Q(b,{el:1,tag:1,id:1}),c=function(a,c,d){c=e(0,c);for(var g,h=0,l=(g=b.getTag())?a.getElementsByTagName(g):[];g=l[h++];)k(g,a)&&T(g,d)&&c.push(g);return c}):c=function(a,c,d){c=e(0,c);for(var g=0,h=b.getTag(),h=h?a.getElementsByTagName(h):[];a=h[g++];)T(a,d)&&c.push(a);return c};return na[b.query]=c},B={},z={},C=function(a){var b=r(c(a));if(1==b.length){var d=ia(b[0]);
return function(a){if(a=d(a,[]))a.nozip=!0;return a}}return function(a){a=e(a);for(var c,d,g=b.length,h,k,l=0;l<g;l++){k=[];c=b[l];d=a.length-1;0<d&&(h={},k.nozip=!0);d=ia(c);for(var m=0;c=a[m];m++)d(c,k,h);if(!k.length)break;a=k}return k}},Z=q("ie")?"commentStrip":"nozip",N=!!h.doc.querySelectorAll,E=/\\[>~+]|n\+\d|([^ \\])?([>~+])([^ =])?/g,F=function(a,b,c,d){return c?(b?b+" ":"")+c+(d?" "+d:""):a},ca=/([^[]*)([^\]]*])?/g,J=function(a,b,c){return b.replace(E,F)+(c||"")},G=function(a,b){a=a.replace(ca,
J);if(N){var c=z[a];if(c&&!b)return c}if(c=B[a])return c;var c=a.charAt(0),d=-1==a.indexOf(" ");0<=a.indexOf("#")&&d&&(b=!0);if(!N||b||-1!="\x3e~+".indexOf(c)||q("ie")&&-1!=a.indexOf(":")||l&&0<=a.indexOf(".")||-1!=a.indexOf(":contains")||-1!=a.indexOf(":checked")||-1!=a.indexOf("|\x3d")){var e=a.match(/([^\s,](?:"(?:\\.|[^"])+"|'(?:\\.|[^'])+'|[^,])*)/g);return B[a]=2>e.length?C(a):function(a){for(var b=0,c=[],d;d=e[b++];)c=c.concat(C(d)(a));return c}}var g=0<="\x3e~+".indexOf(a.charAt(a.length-
1))?a+" *":a;return z[a]=function(b){try{if(9!=b.nodeType&&!d)throw"";var c=b.querySelectorAll(g);c[Z]=!0;return c}catch(e){return G(a,!0)(b)}}},K=0,L=q("ie")?function(a){return b?a.getAttribute("_uid")||a.setAttribute("_uid",++K)||K:a.uniqueID}:function(a){return a._uid||(a._uid=++K)},T=function(a,b){if(!b)return 1;var c=L(a);return b[c]?0:b[c]=1},ja=function(a){if(a&&a.nozip)return a;if(!a||!a.length)return[];if(2>a.length)return[a[0]];var c=[];K++;var d,e;if(q("ie")&&b){var g=K+"";for(d=0;d<a.length;d++)(e=
a[d])&&e.getAttribute("_zipIdx")!=g&&(c.push(e),e.setAttribute("_zipIdx",g))}else if(q("ie")&&a.commentStrip)try{for(d=0;d<a.length;d++)(e=a[d])&&D(e)&&c.push(e)}catch(h){}else for(d=0;d<a.length;d++)(e=a[d])&&e._zipIdx!=K&&(c.push(e),e._zipIdx=K);return c},U=function(a,c){c=c||h.doc;b="div"===(c.ownerDocument||c).createElement("div").tagName;var d=G(a)(c);return d&&d.nozip?d:ja(d)};U.filter=function(a,b,c){for(var e=[],h=r(b),h=1!=h.length||/[^\w#\.]/.test(b)?function(a){return-1!=g.indexOf(U(b,
d.byId(c)),a)}:Q(h[0]),k=0,l;l=a[k];k++)h(l)&&e.push(l);return e};return U})},"dojo/ready":function(){define(["./_base/kernel","./has","require","./domReady","./_base/lang"],function(d,q,g,m,h){var c=0,n=[],l=0;q=function(){c=1;d._postLoad=d.config.afterOnLoad=!0;b()};var b=function(){if(!l){for(l=1;c&&(!m||0==m._Q.length)&&(g.idle?g.idle():1)&&n.length;){var a=n.shift();try{a()}catch(b){if(b.info=b.message,g.signal)g.signal("error",b);else throw b;}}l=0}};g.on&&g.on("idle",b);m&&(m._onQEmpty=b);
var a=d.ready=d.addOnLoad=function(a,c,g){var l=h._toArray(arguments);"number"!=typeof a?(g=c,c=a,a=1E3):l.shift();g=g?h.hitch.apply(d,l):function(){c()};g.priority=a;for(l=0;l<n.length&&a>=n[l].priority;l++);n.splice(l,0,g);b()},r=d.config.addOnLoad;if(r)a[h.isArray(r)?"apply":"call"](d,r);d.config.parseOnLoad&&!d.isAsync&&a(99,function(){d.parser||(d.deprecated("Add explicit require(['dojo/parser']);","","2.0"),g(["dojo/parser"]))});m?m(q):q();return a})},"dojo/domReady":function(){define(["./has"],
function(d){function q(a){b.push(a);l&&g()}function g(){if(!a){for(a=!0;b.length;)try{b.shift()(h)}catch(c){}a=!1;q._onQEmpty()}}var m=function(){return this}(),h=document,c={loaded:1,complete:1},n="string"!=typeof h.readyState,l=!!c[h.readyState],b=[],a;q.load=function(a,b,c){q(c)};q._Q=b;q._onQEmpty=function(){};n&&(h.readyState="loading");if(!l){var r=[],k=function(a){a=a||m.event;l||"readystatechange"==a.type&&!c[h.readyState]||(n&&(h.readyState="complete"),l=1,g())},e=function(a,c){a.addEventListener(c,
k,!1);b.push(function(){a.removeEventListener(c,k,!1)})};if(!d("dom-addeventlistener")){var e=function(a,c){c="on"+c;a.attachEvent(c,k);b.push(function(){a.detachEvent(c,k)})},D=h.createElement("div");try{D.doScroll&&null===m.frameElement&&r.push(function(){try{return D.doScroll("left"),1}catch(a){}})}catch(p){}}e(h,"DOMContentLoaded");e(m,"load");"onreadystatechange"in h?e(h,"readystatechange"):n||r.push(function(){return c[h.readyState]});if(r.length){var w=function(){if(!l){for(var a=r.length;a--;)if(r[a]()){k("poller");
return}setTimeout(w,30)}};w()}}return q})}}});(function(){var d=this.require;d({cache:{}});!d.async&&d(["dojo"]);d.boot&&d.apply(null,d.boot)})();
//# sourceMappingURL=dojo.js.map